### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mrh1997** [gjhiggins/tempita#2]
This module seems to be broken on Python 3.
The cython/Cython project uses a patched version of tempita (see https://github.com/cython/cython/tree/9ef0f0aebaae255c4aa08f528760eb7da10ec3a4/Cython/Tempita) that works with python 3.

Maybe you could take over their changes to avoid getting a lot of different implementations of tempita...

**Comment by gjhiggins** [comment]
++ This module seems to be broken on Python 3.

In what way and which version of Python 3?

**Comment by mrh1997** [comment]
I tested it on Python 3.4

The first two problems were importing ```quote``` from ```urllib``` (https://github.com/gjhiggins/tempita/blob/master/tempita/__init__.py#L35) and importing ```cStringIO``` (https://github.com/gjhiggins/tempita/blob/master/tempita/__init__.py#L38).

Thereafter I stopped doing further tests, but I assume that there will be more problems.

**Comment by gjhiggins** [comment]
I dunno, I added Python3.4 to the test config and the continuous integration tests (the doctests are the originals, as written by Ian.) show green across the board:
[https://travis-ci.org/gjhiggins/tempita](https://travis-ci.org/gjhiggins/tempita)

The 2-3 conversion is handled automatically by `setup.py`.

Do you have tox? If so, you could try `tox -e py34`, see if that works.

**Comment by mrh1997** [comment]
The problem with the automatic 2to3 convertion approach is, that tempita cannot be copied into libraries that offer python 2 and python 3 compatibility via a single source file (without need for being converted). There I need a single module file that can be imported by the librarys modules.

But exactly copying tempita into a library is the strength of tempita, as its small footprint does not have a big impact on the librarys total size. And delivering tempita as part of a library instead of referring to an external template engine in the python path has the big advantage, that the library runs out of the box.

**Comment by charris** [comment]
There is also a problem with running tempita from the command line with python 3 as it read files in binary (bytes) and tries to parse them as strings. That raises an error. I would suggest reading files as simple text, or perhaps latin1 as the latter allows the use of all 256 byte values.

**Comment by charris** [comment]
Having a single code base isn't that difficult these days.

**Comment by fboender** [comment]
@charris You can (and should) use the `encoding=` argument to let Tempita know what encoding your template is in, as it can't guess it.

    t = tempita.Template.from_filename('test.tpl', encoding='utf8')

There really isn't such a thing as 'simple text' unfortunately. Latin1 seems like a bad default encoding. UTF8 would be better, as it has been the standard for years now.

Perhaps Tempita should default to utf8, given that it does raise an error when leaving out the `encoding` argument.

**Comment by charris** [comment]
I'm talking about the command line usage, `python -m tempita <infile> <outfile>` where the read is part of tempita. See line 1170 in `__init__.py` where `f = open(template_name, 'rb')`.

**Comment by gjhiggins** [comment]
(Somewhat crudely) fixed in commit 6cdd36dc and later:

six added and used to kluge up Py2/3 single source; doctests properly enabled; file read with PY3 is  decoded as latin-1 by default.

Haven't investigated command line usage, all I see is:

`No module named tempita.__main__; 'tempita' is a package and cannot be directly executed`

If problems persist, please (re-)raise as a separate issue.
