### ISSUE TITLE
[HTMLTemplate] Content inside "def" is HTML encoded

### ISSUE THREAD

**Issue by dalbani** [gjhiggins/tempita#5]
Given this code:
```python
from tempita import HTMLTemplate

TEMPLATE = """
<div>Hi <span>{{name}}</span>!</div>

{{def repeat_name(name)}}
<div>I repeat, {{name}}</div>
{{enddef}}

{{repeat_name(name)}}
"""

name = 'B<O>P'

template = HTMLTemplate(TEMPLATE)
print(template.substitute(locals()))
```

The following get printed:

```plain
<div>Hi <span>B&lt;O&gt;P</span>!</div>
&lt;div&gt;I repeat, B&amp;lt;O&amp;gt;P&lt;/div&gt;
```

See that the `<div>` within `def repeat_name()` is **also** HTML encoded, whereas I expected it only for `{{name}}`, as in the first line.

Should this considered a bug? What workaround could I use?

**Comment by fboender** [comment]
I wouldn't consider this a bug, since HTMLTemplates are specifically meant for automatic escaping of HTML. I can think of two workarounds:

* Don't use HTMLTemplate
* Mark the function call as not having to be escaped. So instead of:

    {{repeat_name(name)}}

You'd say:

    {{repeat_name(name)|html}}

**Comment by dalbani** [comment]
@fboender: your solution works just fine, I now get:

```<div>I repeat, B&lt;O&gt;P</div>```

Thanks! I close this issue then.
